# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Hugo Lime"
license = "MIT"
licenselink = "https://github.com/uicardiodev/hugo-lime/blob/master/LICENSE.md"
description = ""
homepage = "http://uicard.io/products/green-paper"
tags = ["minimal","blog","services","responsive","bootstrap","uicardio","illustrations"]
features = ["cover","pricing","faq","parteners","blog","work","portfolio","contact","illustrations"]
min_version = "0.47.1"

[author]
  name = "UICardio"
  homepage = "https://uicard.io/products/sodium-hugo-theme"

[developer]
	name = "Arvind"
	homepage = "https://heyarviind.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""